export const GAME_LAUNCHER_ERROR_DIAGNOSTICS = {
    ERROR_LATENCY_USER_NAVIGATION_THRESHOLD_MS: 1000,
    ERROR_LATENCY_TIMEOUT_THRESHOLD_MS: 5000,
    ERROR_CATEGORY_USER_NAVIGATION: "userNavigation",
    ERROR_CATEGORY_NETWORK_ERROR: "networkError",
    ERROR_CATEGORY_TIMEOUT: "timeout",
    ERROR_CATEGORY_UNKNOWN: "unknown",
} as const
